webserver:
  bindaddr: "127.0.0.1"
  port: 1765
  publicaddr: "https://inviterr.example.xyz"
  tls:
    enabled: false
    cert: "cert.pem"
    key: "key.pem"

jellyfin:
  baseURL: "http://localhost:8096"
  apiKey: "your-jellyfin-api-key"
  
jellyseerr:
  baseURL: "http://localhost:5055"
  apiKey: "your-jellyseerr-api-key"

database:
  type: "postgres"
  postgres:
    host: "localhost"
    port: 5432
    database: "inviterr
    username: "inviterr"
    password: "inviterr"