webserver:
  bindaddr: "127.0.0.1:8080"
  publicaddr: "https://inviterr.example.xyz"
  tls:
    enabled: false
    cert: "cert.pem"
    key: "key.pem"

jellyfin:
  baseURL: "http://localhost:8096"
  apiKey: "your-jellyfin-api-key"
  username: "your-username"
  password: "your-password"
jellyseerr:
  baseURL: "http://localhost:5055"
  apiKey: "your-jellyseerr-api-key"
